language: python
python:
- '3.6'
branches:
  only:
  - master
sudo: false
cache:
  apt: true
  pip: true
  directories: 
addons:
  apt:
    packages:
    - qtbase5-dev
install:
- pip install cx_freeze==6.0b1
- pip install coveralls pytest
- pip install git+https://github.com/lbl-camera/Xi-cam.core.git
- pip install git+https://github.com/lbl-camera/Xi-cam.plugins.git
- pip install git+https://github.com/lbl-camera/Xi-cam.gui.git
- pip install .
script:
- pip install pylint twine wheel
- 'pylint xicam --errors-only || :'
- pip install coverage
- sh -e /etc/init.d/xvfb start
- sleep 3
- 'pytest . || :'
- python setup.py install
after_success:
- pip install codecov --upgrade
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: ronpandolfi
  password:
    secure: ASUCtdOW5LmJYLjsndklOKuzBHxmK0lTNus1154Fpus8h7h6xP3dQbux68rK91TtC7fj//2K+85GPqD1Fd5war/yYm45rFQUEyzCze6AV9Skj4D72jrc0PIKO2hGBh/7rnSSg6dxe6Lao9xNu4fdV1dKyxLZSHXSeXPu3tZKtP9A6gDjr2MYh5Tiq4B3GKE1f4gBDS0M8BeV7iObFFpJ5BPZP5uCOsWlXG6j0Q6so7bYrvx3EH4ZSuYXqNJZmaShMhvfvf3G9eDvm2Ruig8yqu+5iTkVih9/2e0Z87EtiOcMqTw/q5lhXiimX97vFmWnl2pzh5I4mf61/wdye6rU1HngXXKNeJ8ERTR3h9uMzdu8nH9TAXlGmxW4hP39oFgiEmn9FrqqUO8oW32q6CDaXTvG3dB6Kgbac2dNDwm+VtaKiFvAfTSrksU83tPvvITyGm/XKAZO0qM6gEli65AE9gVx3wGS1dDHnGjkzPVmNSH4pRqOXrqP3JBWvCcsyuLVON1cTwHUNK5o6ScbxiN3h6B1SWu0SGCH4kXhk8euZ+xLx9NRj0Ajyj7Xsa5uU26gqT4y6UYXSlXQT7LP64aayw9vZZcOnnfteioW278Q+kj5BLJjKe8kQr38eO2XmW5e+FerfgQ6C9fuoiGs2cdTMeL3om4kG3eYPWIT0yiQ+iQ=
  distributions: sdist bdist_wheel bdist_egg
