language: python
python:
- '3.6'
branches:
  only:
  - master
sudo: false
cache:
  apt: true
  pip: true
  directories:
# Attempt to save virtualenv between builds; might not be working
#  - /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages
#  - /home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python.7/site-packages
#  - /usr/lib/python2.7/dist-packages
addons:
  apt:
    packages:
    - qtbase5-dev
install:
- pip install cx_freeze==6.0b1
- pip install coveralls pytest
- pip install git+https://github.com/lbl-camera/Xi-cam.core.git
- pip install git+https://github.com/lbl-camera/Xi-cam.plugins.git
- pip install git+https://github.com/lbl-camera/Xi-cam.gui.git
- pip install .
script:
- pip install pylint
# always returns exit code 0; Write the errors but not cause failure
- "pylint xicam --errors-only || :"
- pip install coverage
#- coverage run xicam/test.py
- "sh -e /etc/init.d/xvfb start" # start xvfb server to buffer gui
- sleep 3 # give xvfb some time to start
- pytest .
- python setup.py install
- python setup.py bdist_wheel
- python setup.py sdist
- python setup.py bdist_egg
- python setup.py build_exe
- twine upload dist/*
after_success:
- pip install codecov --upgrade
- bash <(curl -s https://codecov.io/bash)

