matrix:
  include:
  - os: linux
    language: python
    python: 3.7
    services:
    - xvfb
    before_install:
    - python --version
    - pip install --upgrade pip
    - export DISPLAY=:99.0
    after_success:
    - pip install .[docs]
    - "(cd docs && make html)"
    - bash <(curl -s https://codecov.io/bash)
  - os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.5
    after_script:
    - pyinstaller --clean --onefile --noconsole --paths C:\Windows\System32\downlevel Xi-cam.spec
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

env: TRAVIS=True

cache:
  apt: true
  pip: true

addons:
  apt:
    packages:
    - qtbase5-dev

before_install:
- python --version

install:
- pip install --upgrade attrs>=17.4.0
- pip install --upgrade setuptools wheel
- pip install .[pyqt5,tests,freeze]

script:
- 'pylint xicam --errors-only || :'
- 'pytest --cov=xicam --cov-config=.coveragerc . || :'

deploy:
  skip_cleanup: true
  provider: pypi
  user: ronpandolfi
  password:
    secure: "b/9PvaXVH7KaOoed5jlnaHFiMOqC4/5j/Zomjo8XdMz+Qn5iOjPJTwpXhkQY4znzDLf9Jikqmnve9j2YCuLDdgENg4QTNBKIArqKZFxgVbMimQi27ixEj1XB+dmvIuG23Qc5fFlc4t5miGUMJElRIU7CH5bObPDkne5SydgkivW1G2h1E3NkF7CqJbkYjZzOifA9BGkvTtxiDKHQndPYfszG7H88uOZ2m7iQKhSv7NcpoCadeAlRZ5Pt4NMaOx1sJTNL1okj1jv0eaBcW8wK4mMfYCQ/7hglwxddfF7rycuauSBVAJ6/nybc+z6dow/nxYFu7DpNV6ixALbn3PcwSsH8ahGaZQvC7FIxbyz1eq+7K2+ps1SF3A2VqG1/XXrGVNZN6EWRzyDlZwZuby6EKdNC4ZuijipH8bMZtt1Qg+/rVGZPdoT93AsuF4diX/mUk98bK9F2z3+96Hh0YoFE96rKFPExy7uuGbRYSLT1TT/962OxrcOZ2PjRKexk5+HOs6Z9Z94T+3GshyGz4jO/cJM0gDIxLbo35ehrYKxYPqY9CV3/Yn2jcuoTM+H3cKIJU7W3Y5RHMbNLehG+ScHrcT8LalXUQjxKRXTaBjOpq4D15swUmu1fUwZMamPgnuo61Xt1akITP+Fp/eRWOvIBOo3yuM6p2P1GUrc+6JvB5Tk="
  distributions: sdist bdist_wheel bdist_egg
  on:
    tags: true
    os: linux
