matrix:
  include:
  - os: linux
    language: python
    python: 3.7
    services:
    - xvfb
    before_install:
    - python --version
    - pip install --upgrade pip
    - export DISPLAY=:99.0
    after_success:
    - pip install .[docs]
    - "(cd docs && make html)"
    - bash <(curl -s https://codecov.io/bash)
  - os: windows
    language: shell
    before_install:
    - choco install python --version 3.7.5
    after_script:
    - pyinstaller --clean --onefile --noconsole --paths C:\Windows\System32\downlevel
      Xi-cam.spec
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
env: TRAVIS=True
cache:
  apt: true
  pip: true
addons:
  apt:
    packages:
    - qtbase5-dev
before_install:
- python --version
install:
- pip install --upgrade attrs>=17.4.0
- pip install --upgrade setuptools wheel
- pip install .[pyqt5,tests,freeze]
script:
- 'pylint xicam --errors-only || :'
- 'pytest --cov=xicam --cov-config=.coveragerc . || :'
deploy:
  cleanup: false
  provider: pypi
  username: ihumphrey
  password: "LAkK6tq+rovaDus/b5O7p/J2FCiLwyLl46I+r6lNdxFvwTW+XQUbSirlsqztrVn4aoaFQDhtIbjh+UgSIKLl9GYMUuU6S4wLGIu1E8uqAUsoVeoThyuX5gcpJpyrueVBUudkjCjSabUUzO713dLCdyoXtEH//ihTHsqSLA+/XaxmpilVd0dq71+D8+xVgBhLb6XTPU740IqgiOeYClqj8zn2T7M+Xp5UfA8mXNZ2LY76BAikeGpwyqiMANRCX9B+rc+C4YoNiQzCD7lsjj89Mfz5MdZkxcGS79oVbBQbtue2KvzYEHKDEPgnrgflK6supEyOtZQ+34pT7xKjLq32AUG5JLHLUuNhrYDMiSIu5VxVy+cMykK2C7zTzfL/MnZeHbDya0awlP+ZevMoKOiaLKKBNSRsxhzGUgBQrTTqMmOerOJLBK4A0DMdglTHTZIxITiaGq6n02ob553V5vvorl/lyOqEgGinRe+LFqxWTrMWt3ixxO8HBtbdSuEfDLNiOrbVzGSw5Dm125gxKm4vwPdTBSkFi0Tzprkjck2im3W/EmEXpcOUYw41YH4Any4RKdVblbtTOAGmr/hsxO7H/wdBjsy3r+oFEbB3RtfFV+k4UkPrBMU6J4Ze3ojmgpM6fyYNltjzzggIC5zWX3+zmIgvyEJvGSC0mIAas56Ry+4="
  edge: true
  distributions: sdist bdist_wheel bdist_egg
  on:
    tags: true
    os: linux
