environment:
  matrix:
    - PYTHON: "C:\\Python36"
  TWINE_USERNAME: rp

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'

install:

  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install pyinstaller"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install twine"
  - git clone http://www.github.com/lbl-camera/Xi-cam
  - git clone http://www.github.com/lbl-camera/Xi-cam.core
  - git clone http://www.github.com/lbl-camera/Xi-cam.plugins
  - git clone http://www.github.com/lbl-camera/Xi-cam.gui
  - pip install Xi-cam.core/
  - pip install Xi-cam.plugins/
  - pip install Xi-cam.gui/
  - pip install Xi-cam/
#  - build.bat
  - pyinstaller Xi-cam/Xi-cam.spec


build: off

artifacts:
  - path: dist\*

on_finish:
  # Remove old or huge cache files to hopefully not exceed the 1GB cache limit.
  #
  # If the cache limit is reached, the cache will not be updated (of not even
  # created in the first run). So this is a trade of between keeping the cache
  # current and having a cache at all.
  # NB: This is done only `on_success` since the cache in uploaded only on
  # success anyway.
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -mtime +360 -delete
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -type f -size +10M -delete
  - C:\cygwin\bin\find "%LOCALAPPDATA%\pip" -empty -delete
  # Show size of cache
  - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"

on_success:
  - twine upload


deploy:
  # description: 'Release description'
  provider: GitHub
  auth_token:
    secure: dLIUT4nVPzgnpvNg4rKiX26tG8Zb7Ttb0ZSGxi1KlAwpb+xInWRG88l8ck2/YwoT
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
